# Generated by Django 4.0.4 on 2022-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_familia',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mi_familia',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mi_familia',
            name='ocupacion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mi_familia',
            name='parentaje',
            field=models.CharField(max_length=40),
        ),
    ]
