# Generated by Django 4.0.4 on 2022-04-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreapp', '0002_alter_mi_familia_apellido_alter_mi_familia_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mi_familia',
            name='fecha_nac',
        ),
    ]
